
from datetime import date
from typing import Protocol


class ExpenseStatsRepository(Protocol):
    
    def month_summary_stats(self, start_date: date, end_date: date) -> tuple[int, int]: ...
    
    def top_categories_by_amount(self, start_date: date, end_date: date, limit: int) -> list[tuple[str, int]]: ...
    
    def top_wallets_by_amount(self, start_date: date, end_date: date, limit: int) -> list[tuple[str, int]]: ...
    
    def summary_range_stats(self, start_date: date, end_date: date) -> tuple[int, int]: ...
    
    def by_category_stats(self, start_date: date, end_date: date) -> list[tuple[str, int, int]]: ...
    
    def by_wallet_stats(self, start_date: date, end_date: date) -> list[tuple[str, int, int]]: ...
    
    def by_day_stats(self, start_date: date, end_date: date) -> list[tuple[str, int, int]]: ...
    