
class DomainError(Exception): ...

class InvalidAmount(DomainError): ...

class ExpenseDataError(DomainError): ...

class ExpenseAlreadyExists(DomainError): ...

class ExpenseNotFound(DomainError): ...